title: テスト
remote_theme: "jekyll/minima@1e8a445"
#     * classic            Default, light color scheme.
#     * dark               Dark variant of the classic skin.
#     * auto               Adaptive skin based on the classic and dark skins.
#     * solarized-light    Light variant of solarized color scheme.
#     * solarized-dark     Dark variant of solarized color scheme.
#     * solarized          Adaptive skin for solarized color scheme skins.
skin: dark
hide_site_feed_link: true
plugins:
 - jekyll-feed
 - jekyll-seo-tag
